/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.12
 * Generated at: 2020-01-25 16:53:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ui_002dfiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class description_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1579971159733L));
    _jspx_dependants.put("jar:file:/D:/JAVA%20code%20n%20material/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/CuMerchandise/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html lang=\"\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Product Detail</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta name=\"author\" content=\"Aniruddha and Abhishek Bansal\" />\r\n");
      out.write("<meta name=\"description\" content=\"will show product detail\" />\r\n");
      out.write("\r\n");
      out.write("<!-- including style sheets -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../style-files/home-root-style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../style-files/home-header-style2.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../style-files/home-footer-style2.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../style-files/description.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- page tab icon -->\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\"\r\n");
      out.write("\thref=\"../resource/icons/tab_logo.png\" />\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\"\r\n");
      out.write("\thref=\"../resource/icons/tab_logo.png\" sizes=\"32x32\"/>\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\"\r\n");
      out.write("\thref=\"../resource/icons/tab_logo.png\" sizes=\"48x48\"/>\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\"\r\n");
      out.write("\thref=\"../resource/icons/tab_logo.png\" sizes=\"96x96\"/>\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\"\r\n");
      out.write("\thref=\"../resource/icons/tab_logo.png\" sizes=\"144x144\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- including jsp tag library -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<header id=\"navBar\">\r\n");
      out.write("\t\t<!-- logo -->\r\n");
      out.write("\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t<label class=\"logo_cu\">CU</label><label class=\"logo_m\">Merchandise</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- search area -->\r\n");
      out.write("\t\t<div style=\"padding: 5;\">\r\n");
      out.write("\t\t\t<input id=\"search\" placeholder=\"Search Here\"> <img\r\n");
      out.write("\t\t\t\tid=\"search_ic\" src=\"../resource/icons/search_ic.png\" alt=\"search\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- other details -->\r\n");
      out.write("\t\t<div class=\"detail\">\r\n");
      out.write("\t\t\t<img style=\"height: 20px;\" src=\"../resource/icons/email_ic.png\" /> <label\r\n");
      out.write("\t\t\t\tstyle=\"position: absolute; margin-left: 2;\">brandshop@cumail.in</label>\r\n");
      out.write("\t\t\t<br /> <img style=\"position: absolute; height: 20px; margin-top: 5;\"\r\n");
      out.write("\t\t\t\tsrc=\"../resource/icons/call_ic.png\" />\r\n");
      out.write("\t\t\t<wbr />\r\n");
      out.write("\t\t\t<label style=\"position: absolute; margin-left: 22; margin-top: 6px;\">9520401457</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<main>\r\n");
      out.write("\t\t<div class=\"mainBody\" id=\"description\">\r\n");
      out.write("\t\t\t<div class=\"product_image\">\r\n");
      out.write("\t\t\t\t<div class=\"col0\">\r\n");
      out.write("\t\t\t\t\t<div class=\"image\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"../resource/slider/01.jpg\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"image\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"../resource/slider/01.jpg\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"image\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"../resource/slider/01.jpg\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col1\">\r\n");
      out.write("\t\t\t\t\t<img src=\"../resource/slider/01.jpg\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"product_detail\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<label class=\"product_name\">Modo Rapido</label> <br /> <label\r\n");
      out.write("\t\t\t\t\tclass=\"about_product\">Men Maroon Printed Round Neck T-shirt</label>\r\n");
      out.write("\t\t\t\t<br /> <br />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label class=\"price_product1\">Rs. 519</label> <label\r\n");
      out.write("\t\t\t\t\t\tclass=\"price_product2\">Rs.649</label> <label\r\n");
      out.write("\t\t\t\t\t\tclass=\"price_product3\">(20%OFF)</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<label class=\"taxes\">inclusive of all taxes</label> <br /> <br />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label class=\"select_size\">SELECT SIZE</label> <label\r\n");
      out.write("\t\t\t\t\t\tclass=\"size_chart\">SIZE CHART ></label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"size_div\">\r\n");
      out.write("\t\t\t\t\t<span class=\"size\">S</span> <span class=\"size\">M</span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"size\">L</span> <span class=\"size\">XL</span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"size\">XXL</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"buy_now\">\r\n");
      out.write("\t\t\t\t\t<Button class=\"bag\">ADD TO BAG</Button>\r\n");
      out.write("\t\t\t\t\t<Button class=\"buy\">BUY NOW</Button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"details\">PRODUCT DETAILS</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"name\">Maroon and black printed T-shirt, has a\r\n");
      out.write("\t\t\t\t\tround neck, long sleeves</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</main>\r\n");
      out.write("\r\n");
      out.write("\t<footer></footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
